site_name: 棒无の知识库
site_url: https://base.bangwu.top
site_author: 棒无
site_description: 红温小丑：一个小白友好的教程网站，作者：棒无
copyright: Copyright © 2023-present <a href="https://github.com/markbang">棒无</a>

nav:
  - 主页:
      - 首页: index.md
      - 代码: code.md
  - 后端:
      - 后端: backend/index.md
      - Python:
          - Python: backend/Python/index.md
          - 爬虫: backend/Python/spider/index.md
          - 反爬虫: backend/Python/spider/anti-spider.md
          - FastAPI: backend/Python/fastapi.md
          - 常用库:
              - Httpx: backend/Python/libs/httpx.md
              - 词云: backend/Python/libs/wordcloud.md
              - Matplotlib: backend/Python/libs/matplotlib.md
      - Go: backend/Go/index.md
      - 数据库: backend/SQL/index.md
  - 前端:
      - 前端: frontend/index.md
      - Vue: frontend/Vue/index.md
      - Nextjs: frontend/Nextjs/index.md
      - TailwindCSS: frontend/TailwindCSS/index.md
  - 客户端:
      - 客户端: software/index.md
      - Tauri: software/tauri.md
  - 算法:
      - 算法: algo/index.md
      - 滑动窗口: algo/sliding_window.md
      - 位操作: algo/bit.md
  - 软件:
      - 软件: apps/index.md
      - Apifox: apps/Apifox.md
      - Barrier: apps/Barrier.md
      - CherryStudio: apps/CherryStudio.md
      - Cursor: apps/Cursor.md
      - iTab: apps/iTab.md
      - Pyenv: apps/Pyenv.md
      - Rclone: apps/Rclone.md
      - Rye: apps/Rye.md
      - Scoop: apps/Scoop.md
      - ShareX: apps/ShareX.md
      - starship: apps/starship.md
      - Typora: apps/Typora.md
      - 息知: apps/Xizhi.md
  - 环境:
      - 环境: env/index.md
      - 笔试: env/笔试.md
      - 面经: env/面经.md
      - markdown: env/markdown.md
      - Github Workflow: env/github-workflow.md
      - Caddy 服务器: env/Caddy.md
      - Supervisor: env/supervisor.md
      - 博客:
          - Fuwarui: env/Fuwari.md
          - 图床: env/imgbed.md
      - Docker:
          - Docker: env/docker.md
          - Docker Compose: env/docker-compose.md
      - Jupyter: env/Jupyter.md
  - 一人之下:
      - 一人之下: yrzx/index.md
      - 人物:
          - 张楚岚: yrzx/zcl.md
          - 冯宝宝: yrzx/fbb.md
      - 漫画: yrzx/yiren.md
      - 锈铁篇: yrzx/xiutie.md
  - 关于:
      - 关于: about/index.md
      - 站点: about/site.md
      - 课程复习:
          - 电子商务: about/courses/电子商务.md
          - 管理信息系统: about/courses/管理信息系统.md
          - 数据可视化: about/courses/数据可视化.md
          - 知识管理: about/courses/知识管理.md

theme:
  name: material
  logo: assets/joker.png
  favicon: assets/joker.png
  custom_dir: overrides
  language: zh
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/brightness-auto
        name: ''
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-night
        name: ''
    - media: '(prefers-color-scheme: dark)'
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: ''
  font:
    text: Roboto
    code: Roboto Mono
extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/markbang
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/markbangwu
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@bangwu
    - icon: fontawesome/solid/blog
      link: https://bangwu.top
extra_css:
  - stylesheets/extra.css
plugins:
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      fallback_to_build_date: true
  - search: # 搜索
      lang:
        - en
        - ja # 日文，也勉强支持中文
      separator: '[\s\-\.]+' # 分词分隔符
      # prebuild_index: true # 预制索引，不成功
  - gh-admonitions
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.details

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.zhihu.com/mathjax@3/es5/tex-mml-chtml.js
