site_name: 棒无の知识库
site_url: https://base.bangwu.top
site_author: 棒无
site_description: 红温小丑：一个小白友好的教程网站，作者：棒无
copyright: Copyright © 2023-present <a href="https://github.com/markbang">棒无</a>

nav:
  - 主页:
      - 首页: index.md
      - 代码: code.md
  - 代码: code/index.md
  - 软件:
      - 软件: apps/index.md
      - APIfox: apps/APIfox.md
  - 环境: env/index.md
  - 一人之下: yrzx/index.md
  - 关于: about/index.md

theme:
  name: material
  logo: assets/joker.png
  favicon: assets/joker.png
  custom_dir: overrides
  language: zh
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/brightness-auto
        name: ''
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-night
        name: ''
    - media: '(prefers-color-scheme: dark)'
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: ''
  font:
    text: Roboto
    code: Roboto Mono
extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/markbang
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/markbangwu
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@bangwu
    - icon: fontawesome/solid/blog
      link: https://bangwu.top
plugins:
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      fallback_to_build_date: true
  - search: # 搜索
      lang:
        - en
        - ja # 日文，也勉强支持中文
      separator: '[\s\-\.]+' # 分词分隔符
      # prebuild_index: true # 预制索引，不成功
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.details

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.zhihu.com/mathjax@3/es5/tex-mml-chtml.js
